# Generated by Django 4.2.5 on 2023-10-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_pedido_producto_marca_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=60)),
                ('cliente', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
