# Generated by Django 4.2.5 on 2023-10-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_cliente_delete_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerveceria',
            name='pais',
        ),
    ]
